### ISSUE TITLE
Search value change is slow

### ISSUE THREAD

**Issue by HugoGresse** [ThomasKientz/mdisearch#1]
When typing in the search bar, I often find myself with missing chars. 
I see the app use Algolia, maybe there is some way to debounce the search by 200ms to speed up the state update on the field value?

**Comment by ThomasKientz** [comment]
Hi @HugoGresse, I have seen this as well. I will look into this soon.

**Comment by ThomasKientz** [comment]
Created an issue on Algolia repo : https://github.com/algolia/vue-instantsearch/issues/1145 but no fixes yet.

**Comment by ThomasKientz** [comment]
In the meantime I have released a temporary fixed.
